# Generated by Django 6.0.1 on 2026-01-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CodeArena_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="total_submissions",
            field=models.IntegerField(default=0),
        ),
    ]
