# Generated by Django 6.0 on 2026-01-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeArena_app', '0002_usermcqattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermcqattempt',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
