# Generated by Django 6.0 on 2026-01-25 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeArena_app', '0003_usermcqattempt_completed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermcqattempt',
            unique_together=set(),
        ),
    ]
