# Generated by Django 6.0 on 2026-01-26 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeArena_app', '0004_alter_usermcqattempt_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.AddField(
            model_name='mcq',
            name='code_snippet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mcq',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('MCQ', 'Simple MCQ'), ('DEBUG', 'Debugging MCQ')], default='MCQ', max_length=10),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], max_length=10),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='CodeArena_app.mcq'),
        ),
        migrations.AlterUniqueTogether(
            name='usermcqattempt',
            unique_together={('user', 'quiz')},
        ),
    ]
