# Generated by Django 6.0.1 on 2026-01-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CodeArena_app", "0003_dailysubmission"),
        ("CodeArena_app", "0004_alter_usermcqattempt_unique_together"),
    ]

    operations = []
