# Generated by Django 6.0 on 2026-01-29 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeArena_app', '0005_alter_quiz_options_mcq_code_snippet_mcq_explanation_and_more'),
        ('CodeArena_app', '0005_merge_20260128_0827'),
    ]

    operations = [
    ]
