# Generated by Django 6.0 on 2026-01-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeArena_app', '0006_merge_20260129_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermcqattempt',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
