# Generated by Django 6.0.1 on 2026-02-02 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CodeArena_app", "0007_exampletestcase_testcase"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testcase",
            name="problem",
        ),
        migrations.DeleteModel(
            name="ExampleTestCase",
        ),
        migrations.DeleteModel(
            name="TestCase",
        ),
    ]
