# Generated by Django 6.0 on 2026-02-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeArena_app', '0008_problemsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
