# Generated by Django 6.0 on 2026-02-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeArena_app', '0009_userprofile_profile_completed'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='CodeArena_a_usernam_4d899b_idx'),
        ),
    ]
