# Generated by Django 6.0 on 2026-02-09 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeArena_app', '0010_alter_user_options_and_more'),
        ('CodeArena_app', '0011_exampletestcase_testcase'),
    ]

    operations = [
    ]
