# Generated by Django 6.0 on 2026-02-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CodeArena_app", "0011_exampletestcase_testcase"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="starter_code_cpp",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="starter_code_java",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="starter_code_python",
            field=models.TextField(blank=True),
        ),
    ]
