# Generated by Django 6.0.1 on 2026-02-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "CodeArena_app",
            "0012_problem_starter_code_cpp_problem_starter_code_java_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="education",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="twitter",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="work_experience",
            field=models.TextField(blank=True),
        ),
    ]
