# Generated by Django 6.0.1 on 2026-02-09 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CodeArena_app", "0012_merge_20260209_1507"),
        ("CodeArena_app", "0013_userprofile_education_userprofile_location_and_more"),
    ]

    operations = []
