# Generated by Django 6.0 on 2026-02-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeArena_app', '0014_merge_20260209_1131'),
        ('CodeArena_app', '0014_merge_20260209_1715'),
    ]

    operations = [
    ]
