# Generated by Django 6.0 on 2026-02-09 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeArena_app', '0015_merge_20260209_1251'),
        ('CodeArena_app', '0015_merge_20260209_2119'),
    ]

    operations = [
    ]
