# Generated by Django 6.0 on 2026-02-09 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeArena_app', '0016_merge_20260210_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='starter_code_cpp',
        ),
    ]
