# Generated by Django 6.0 on 2026-02-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeArena_app', '0017_remove_problem_starter_code_cpp'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['points'], name='CodeArena_a_points_15c52b_idx'),
        ),
    ]
