# Generated by Django 6.0 on 2026-02-10 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CodeArena_app', '0018_contactmessage'),
        ('CodeArena_app', '0018_userprofile_codearena_a_points_15c52b_idx'),
    ]

    operations = [
    ]
