# Generated by Django 6.0.1 on 2026-02-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CodeArena_app", "0019_merge_20260210_1145"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemsubmission",
            name="language_used",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
